import type { Patient } from './types';

// Set base time to 10:00 AM IST (04:30 UTC)
const now = new Date('2024-07-30T04:30:00Z').getTime();
const oneHour = 60 * 60 * 1000;

const generateVitals = (
  count: number,
  hrRange: [number, number],
  spo2Range: [number, number],
  tempRange: [number, number]
) => {
  return Array.from({ length: count }, (_, i) => ({
    timestamp: now - (count - i) * (oneHour / count),
    heart_rate: Math.floor(Math.random() * (hrRange[1] - hrRange[0] + 1) + hrRange[0]),
    spo2: Math.floor(Math.random() * (spo2Range[1] - spo2Range[0] + 1) + spo2Range[0]),
    temperature: parseFloat((Math.random() * (tempRange[1] - tempRange[0]) + tempRange[0]).toFixed(1)),
    respiration_rate: Math.floor(Math.random() * (22 - 16 + 1) + 16),
    movement: Math.random() * 0.5,
  }));
};

export const patients: Patient[] = [
  {
    id: 'p001',
    name: 'Rajesh Kumar',
    avatarUrl: 'https://picsum.photos/seed/p1/100/100',
    age: 72,
    gender: 'Male',
    room: '301A',
    chronicConditions: ['Hypertension', 'Diabetes Type 2'],
    vitals: generateVitals(12, [115, 135], [89, 92], [38.0, 38.8]),
    news2: {
      total_score: 7,
      breakdown: {
        respiration_rate: 2,
        spo2: 2,
        air_or_oxygen: 0,
        systolic_bp: 0,
        heart_rate: 2,
        consciousness: 0,
        temperature: 1,
      },
    },
    anomalyScore: 0.88,
    compositeRisk: { score: 8.5, level: 'HIGH' },
    lastReviewed: { userName: 'Dr. Mehta', timestamp: now - 3 * oneHour },
    riskSummary: 'Elevated heart rate and temperature with low SpO2. History of hypertension and diabetes increases risk. Recommend immediate clinical review.',
    alerts: [
      {
        id: 'a001',
        timestamp: now - 30 * 60 * 1000,
        explanation: 'Patient shows sustained tachycardia and desaturation, with a rising temperature. The combination of these factors alongside a high NEWS2 score indicates significant clinical deterioration.',
      },
    ],
  },
  {
    id: 'p002',
    name: 'Sunita Gupta',
    avatarUrl: 'https://picsum.photos/seed/p2/100/100',
    age: 65,
    gender: 'Female',
    room: '302B',
    chronicConditions: ['COPD'],
    vitals: generateVitals(12, [95, 105], [93, 95], [37.2, 37.8]),
    news2: {
      total_score: 4,
      breakdown: {
        respiration_rate: 1,
        spo2: 1,
        air_or_oxygen: 0,
        systolic_bp: 0,
        heart_rate: 1,
        consciousness: 0,
        temperature: 1,
      },
    },
    anomalyScore: 0.65,
    compositeRisk: { score: 5.2, level: 'MEDIUM' },
    lastReviewed: { userName: 'Dr. Singh', timestamp: now - 1.5 * oneHour },
    riskSummary: 'Slightly elevated heart rate and borderline SpO2. COPD history is a consideration. Monitor closely for changes.',
    alerts: [],
  },
  {
    id: 'p003',
    name: 'Amit Patel',
    avatarUrl: 'https://picsum.photos/seed/p3/100/100',
    age: 81,
    gender: 'Male',
    room: '303C',
    chronicConditions: ['Atrial Fibrillation'],
    vitals: generateVitals(12, [85, 95], [96, 98], [37.0, 37.4]),
    news2: {
      total_score: 1,
      breakdown: {
        respiration_rate: 0,
        spo2: 0,
        air_or_oxygen: 0,
        systolic_bp: 0,
        heart_rate: 1,
        consciousness: 0,
        temperature: 0,
      },
    },
    anomalyScore: 0.32,
    compositeRisk: { score: 2.1, level: 'LOW' },
    lastReviewed: { userName: 'Dr. Sharma', timestamp: now - 45 * 60 * 1000 },
    riskSummary: 'Vitals are largely stable. Heart rate shows some variability consistent with history of Atrial Fibrillation. Routine observation recommended.',
    alerts: [],
  },
  {
    id: 'p004',
    name: 'Meera Das',
    avatarUrl: 'https://picsum.photos/seed/p4/100/100',
    age: 58,
    gender: 'Female',
    room: '304A',
    chronicConditions: [],
    vitals: generateVitals(12, [70, 80], [97, 99], [36.8, 37.1]),
    news2: {
      total_score: 0,
      breakdown: {
        respiration_rate: 0,
        spo2: 0,
        air_or_oxygen: 0,
        systolic_bp: 0,
        heart_rate: 0,
        consciousness: 0,
        temperature: 0,
      },
    },
    anomalyScore: 0.15,
    compositeRisk: { score: 0.8, level: 'LOW' },
    lastReviewed: { userName: 'Dr. Patel', timestamp: now - 2 * oneHour },
    riskSummary: 'Patient stable with all vital signs within normal range. No significant risk factors identified.',
    alerts: [],
  },
  {
    id: 'p005',
    name: 'Suresh Nair',
    avatarUrl: 'https://picsum.photos/seed/p5/100/100',
    age: 79,
    gender: 'Male',
    room: '305B',
    chronicConditions: ['Kidney Disease'],
    vitals: generateVitals(12, [65, 75], [95, 97], [36.7, 37.0]),
    news2: {
      total_score: 0,
      breakdown: {
        respiration_rate: 0,
        spo2: 0,
        air_or_oxygen: 0,
        systolic_bp: 0,
        heart_rate: 0,
        consciousness: 0,
        temperature: 0,
      },
    },
    anomalyScore: 0.21,
    compositeRisk: { score: 1.1, level: 'LOW' },
    lastReviewed: { userName: 'Dr. Sharma', timestamp: now - 8 * oneHour },
    riskSummary: 'Patient stable. Chronic conditions require routine monitoring but current vitals are not concerning.',
    alerts: [],
  },
];
