import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Lightbulb } from 'lucide-react';

type RiskExplanationProps = {
    summary: string;
}

export function RiskExplanation({ summary }: RiskExplanationProps) {
  return (
    <Card>
      <CardHeader className="flex-row items-center gap-4 space-y-0">
        <div className="rounded-full bg-accent/20 p-2 text-accent">
            <Lightbulb className="h-5 w-5 text-accent-foreground" />
        </div>
        <div>
            <CardTitle>AI Risk Summary</CardTitle>
            <CardDescription>Generated by Gemini for explanation.</CardDescription>
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-foreground/90 italic">
          &ldquo;{summary}&rdquo;
        </p>
      </CardContent>
    </Card>
  );
}
